.Dd July 23, 2016
.Dt htpasswd 1
.Sh NAME
.Nm htpasswd
.Nd Create and update user authentication files
.Sh SYNOPSIS
.Nm
.Op Fl cm
.Ar FILE
.Ar USERNAME
.Sh DESCRIPTION
.Nm
is used to create and update the flat-files used to store usernames and
password for basic authentication of HTTP users.  Resources available
from the Merecat web server can be restricted to just the users listed
in the files created by htpasswd.  This program can only be used when
the usernames are stored in a flat-file.
.Pp
This manual page only lists the command line arguments for
.Nm .
For details of the directives necessary to enable user authentication in
the web server, see
.Xr merecat 8 ,
the Merecat httpd README, or the GitHub project home page
.Aq https://github.com/troglobit/merecat .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Create, or recreate the .htpwassd file,
.Ar FILE ,
if it already exists.
.It Fl m
Use MD5 encryption for passwords, this is tested at runtime.  So this
option is simply for compatibility with other similar tools.
.It Ar FILE
Name of the file to contain the user name and password,
usually .htpasswd.  If
.Fl c
is given, this file is created if it does not already exist, or deleted
and recreated if it does exist.
.It Ar USERNAME
The username to create or update in passwdfile,
.Ar FILE .
If username does not exist is this file, an entry is added.  If it does
exist, the password is changed.
.El
.Sh SEE ALSO
.Xr merecat 8
.Sh AUTHOR
Rob McCool.  Modified 29aug97 by Jef Poskanzer to accept new password on
stdin, if stdin is a pipe or file.  This is necessary for use from CGI.
