#!/bin/sh
#
# merecat_wrapper - wrapper script for merecat on FreeBSD
#
# This goes in /usr/local/sbin.  It runs merecat in a loop.  If merecat
# exits then the script restarts it automatically.
#
# The -D flag tells merecat to *not* put itself into the background,
# and the -C flag tells it to get the rest of its configuration from
# the specified config file.

while true ; do
    /usr/local/sbin/merecat -D -C /usr/local/www/merecat_config
    if [ -f /var/run/nologin ] ; then
	exit
    fi
    sleep 10
    egrep ' merecat\[' /var/log/messages |
      tail -33 |
      mail -s "merecat on `hostname` restarted" root
done
