#!/bin/sh

date=`date -u '+%a, %d %b %Y %H:%M:%S %Z'`

cat << EOF
Content-type: text/plain
Expires: $date

CGI printenv

EOF

echo 'Date:'
date
echo
echo 'Id:'
id
echo

exit 0
# That exit is to prevent that scanners
#   report a **possible** vulnerablity
# Comment out that exit to show
# what is in the environment
# and content of "post", if any.

echo 'Env:'
printenv
echo
if [ "$CONTENT_LENGTH" != "" ] ; then
    if [ "$CONTENT_LENGTH" -ne 0 ] ; then
	echo 'Input:'
	echo
	dd bs=1 count=$CONTENT_LENGTH
	echo
    fi
fi
