name: Deb Package Builder

on:
  push:
    branches:
      - debian
  pull_request:
    branches:
      - debian

jobs:
  build-deb:
    name: ubuntu-24.04
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install build dependencies
        run: |
          apt-get -y update
          apt-get -y install git devscripts equivs
      - uses: actions/checkout@v6
      - name: Install package build dependencies
        run: |
          mk-build-deps --install --remove --tool "apt-get -y --no-install-recommends" debian/control
      - name: Build .deb package
        run: |
          dpkg-buildpackage -us -uc -b
      - name: Inspect package
        run: |
          dpkg-deb --info ../merecat_*.deb
          dpkg-deb --contents ../merecat_*.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: merecat-deb-ubuntu-24.04
          path: ../merecat_*.deb
