name: Deb Package Builder

on:
  push:
    branches:
      - debian
  pull_request:
    branches:
      - debian

jobs:
  build-deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install build dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install devscripts equivs
          sudo mk-build-deps --install --remove --tool "apt-get -y --no-install-recommends" debian/control
      - name: Build .deb package
        run: |
          dpkg-buildpackage -us -uc -b
      - name: Inspect package
        run: |
          dpkg-deb --info ../merecat_*.deb
          dpkg-deb --contents ../merecat_*.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: merecat-deb-ubuntu-latest
          path: ../merecat_*.deb
